# Generated by Django 6.0.6 on 2026-06-26 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bar', '0001_initial'),
        ('barbershop', '0001_initial'),
        ('carwash', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('movement_type', models.CharField(choices=[('opening', 'Abertura'), ('withdrawal', 'Sangria'), ('reinforcement', 'Reforço'), ('adjustment', 'Ajuste')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='pos.cashsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('department', models.CharField(choices=[('barbershop', 'Barbershop'), ('bar', 'Bar'), ('carwash', 'Carwash')], max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Em rascunho'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='barbershop.appointment')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='accounts.employee')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.cashsession')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='carwash.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('mpesa', 'M-Pesa'), ('transfer', 'Transferência'), ('other', 'Outro')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.sale')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('item_type', models.CharField(choices=[('product', 'Produto'), ('service', 'Serviço')], max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='bar.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.sale')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='barbershop.service')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
