# Generated by Django 6.0.6 on 2026-08-18 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('barbershop', '0002_alter_service_options_service_subcategory_and_more'),
        ('carwash', '0001_initial'),
        ('customers', '0002_customer_active'),
        ('pos', '0002_sale_amount_paid_sale_balance_due_sale_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalsession',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_sessions', to='barbershop.appointment'),
        ),
        migrations.AddField(
            model_name='operationalsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalsession',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_sessions', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='operationalsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operationalsession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalsession',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_sessions', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='operationalsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalsession',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_sessions', to='carwash.vehicle'),
        ),
        migrations.AlterField(
            model_name='operationalsession',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('waiting', 'Aguardando'), ('in_progress', 'Em atendimento'), ('paused', 'Pausada'), ('ready', 'Pronta'), ('awaiting_payment', 'Aguardando pagamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('basis_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('accrued', 'Acumulada'), ('paid', 'Paga'), ('reversed', 'Estornada')], default='accrued', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='accounts.employee')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='pos.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
