# Generated by Django 6.0.6 on 2026-08-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_operationalsession_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_reprint_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
