# Generated by Django 6.0.6 on 2026-06-26 10:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('business_name', models.CharField(default='O Capitão', max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('receipt_footer', models.TextField(blank=True)),
                ('sync_interval_seconds', models.PositiveIntegerField(default=300)),
                ('enable_bar_module', models.BooleanField(default=True)),
                ('enable_carwash_module', models.BooleanField(default=True)),
                ('allow_walk_in', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
