# Generated by Django 6.0.6 on 2026-06-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='allow_negative_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='appointment_slot_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='settings',
            name='auto_sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='backup_folder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='settings',
            name='business_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='settings',
            name='country',
            field=models.CharField(default='Moçambique', max_length=80),
        ),
        migrations.AddField(
            model_name='settings',
            name='currency_code',
            field=models.CharField(default='MZN', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='currency_symbol',
            field=models.CharField(default='MT', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='settings',
            name='enable_barbershop_module',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='enable_low_stock_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='enable_pos_module',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='enable_reports_module',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='legal_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='settings',
            name='nuit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='settings',
            name='printer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='settings',
            name='receipt_header',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='require_pin_on_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='ssh_tunnel_command',
            field=models.TextField(blank=True, default='ssh -L 5523:127.0.0.1:3306 salacsth@premium342.web-hosting.com -p 21098 -N'),
        ),
        migrations.AddField(
            model_name='settings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='timezone',
            field=models.CharField(default='Africa/Maputo', max_length=60),
        ),
    ]
