# Generated by Django 6.0.6 on 2026-06-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_settings_allow_negative_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ssh_tunnel_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
