# Generated by Django 6.0.6 on 2026-08-18 15:36

from django.db import migrations
import os


def move_password_to_windows_vault(apps, schema_editor):
    Settings = apps.get_model('settings_app', 'Settings')
    password = Settings.objects.exclude(ssh_tunnel_password='').values_list('ssh_tunnel_password', flat=True).first()
    if not password:
        return
    try:
        import keyring
        user = os.environ.get('SSH_USER', 'salacsth')
        host = os.environ.get('SSH_HOST', 'premium342.web-hosting.com')
        keyring.set_password('O Capitao SSH', f'{user}@{host}', password)
    except Exception:
        # Environments without an OS credential vault can keep using SSH_PASSWORD from .env.
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_add_ssh_tunnel_password'),
    ]

    operations = [
        migrations.RunPython(move_password_to_windows_vault, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='settings',
            name='ssh_tunnel_password',
        ),
    ]
