# Generated by Django 6.0.6 on 2026-08-18 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_alter_service_options_service_subcategory_and_more'),
        ('customers', '0002_customer_active'),
        ('pos', '0004_documentsequence_sale_receipt_issued_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('name', models.CharField(default='Fidelização O Capitão', max_length=120)),
                ('points_per_currency', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('currency_value_per_point', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('points_expire_days', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoyaltyLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('entry_type', models.CharField(choices=[('earn', 'Ganho'), ('redeem', 'Resgate'), ('reversal', 'Estorno'), ('adjustment', 'Ajuste')], max_length=20)),
                ('points', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_entries', to='customers.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_entries', to='pos.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('barbershop', 'Barbershop'), ('bar', 'Bar'), ('carwash', 'Carwash')], max_length=20)),
                ('threshold_count', models.PositiveIntegerField(default=4)),
                ('period', models.CharField(choices=[('calendar_month', 'Mês civil')], default='calendar_month', max_length=20)),
                ('reward_type', models.CharField(choices=[('free_eligible_services', 'Serviços elegíveis grátis'), ('percentage', 'Desconto percentual'), ('fixed', 'Desconto fixo')], default='free_eligible_services', max_length=40)),
                ('reward_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_redemptions_per_period', models.PositiveIntegerField(default=0, help_text='Zero significa ilimitado.')),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('eligible_services', models.ManyToManyField(blank=True, related_name='promotions', to='barbershop.service')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRedemption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_redemptions', to='customers.customer')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='customers.promotion')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_redemptions', to='pos.sale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('promotion', 'sale'), name='unique_promotion_sale')],
            },
        ),
    ]
