# Generated by Django 6.0.6 on 2026-06-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reference_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venda'), ('internal_use', 'Uso interno'), ('loss', 'Perda'), ('adjustment', 'Ajuste'), ('transfer', 'Transferência')], default='adjustment', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
