# Generated by Django 6.0.6 on 2026-08-18 15:36

from django.db import migrations, models


def compact_pending_queue(apps, schema_editor):
    SyncQueue = apps.get_model('sync', 'SyncQueue')
    seen = set()
    for item in SyncQueue.objects.filter(status='pending').order_by('-updated_at'):
        key = (item.model_label, item.object_id)
        if key in seen:
            item.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100, unique=True)),
                ('last_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(compact_pending_queue, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='syncqueue',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('model_label', 'object_id'), name='unique_pending_sync_object'),
        ),
    ]
