# Generated by Django 6.0.6 on 2026-08-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_synccursor_syncqueue_next_attempt_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito'), ('failed', 'Falha permanente')], default='pending', max_length=20),
        ),
    ]
