# Generated by Django 6.0.6 on 2026-06-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.CharField(choices=[('bar', 'Bar'), ('barbershop', 'Barbershop'), ('carwash', 'Carwash'), ('shared', 'Partilhado')], default='bar', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('resale', 'Revenda'), ('consumable', 'Consumível'), ('supply', 'Material')], default='resale', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('unit', 'Unidade'), ('bottle', 'Garrafa'), ('pack', 'Pacote'), ('box', 'Caixa'), ('liter', 'Litro'), ('milliliter', 'Mililitro'), ('kilogram', 'Quilograma')], default='unit', max_length=20),
        ),
    ]
