# Generated by Django 6.0.6 on 2026-06-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_product_barcode_product_department_product_item_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['department', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, default='/branding/placeholders/product-default.svg'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='department',
            field=models.CharField(choices=[('bar', 'Bar'), ('barbershop', 'Barbershop'), ('carwash', 'Carwash'), ('shared', 'Partilhado')], default='bar', max_length=20),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bar.productcategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
