# Generated by Django 6.0.6 on 2026-06-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_alter_productcategory_options_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
