# Generated by Django 6.0.6 on 2026-06-26 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('department', models.CharField(choices=[('barbershop', 'Barbershop'), ('carwash', 'Carwash')], max_length=20)),
                ('category', models.CharField(choices=[('corte', 'Corte'), ('barba', 'Barba'), ('pintura', 'Pintura'), ('tratamento', 'Tratamento'), ('lavagem', 'Lavagem'), ('outro', 'Outro')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('department', models.CharField(choices=[('barbershop', 'Barbershop'), ('carwash', 'Carwash')], max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('in_progress', 'Em atendimento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('no_show', 'Falta')], default='scheduled', max_length=20)),
                ('walk_in', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcial'), ('paid', 'Pago')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customers.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='barbershop.service')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
    ]
