# Generated by Django 6.0.6 on 2026-06-26 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['department', 'category', 'subcategory', 'name']},
        ),
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('conflict', 'Conflito')], default='pending', max_length=20)),
                ('department', models.CharField(choices=[('barbershop', 'Barbershop'), ('carwash', 'Carwash')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='barbershop.servicecategory')),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='barbershop.servicecategory'),
        ),
    ]
