import type {
  AppSettings,
  Appointment,
  AuthUser,
  Customer,
  PermissionDefinition,
  Product,
  ProductCategory,
  RoleRecord,
  StockMovement,
  SyncState,
  UserRecord,
  DashboardSummary,
  Service,
  ServiceCategory,
  Vehicle,
} from '../types/models'

export const mockSyncState: SyncState = {
  online: false,
  api_online: true,
  remote_api_online: false,
  database_online: false,
  postgres_online: false,
  pending_count: 7,
  mode: 'offline',
  label: 'Modo local ativo',
  last_error: 'A cloud está indisponível. Os dados continuam seguros no SQLite local.',
}

export const mockDashboard: DashboardSummary = {
  data: new Date().toISOString(),
  total_vendas: 8425,
  totais_por_area: {
    barbershop: 4200,
    bar: 1675,
    carwash: 2550,
  },
  servicos_pendentes: 6,
  caixa_aberto: true,
  estado_sincronizacao: mockSyncState,
  ultima_sincronizacao: null,
}

export const mockCategories: ProductCategory[] = [
  { id: 'cat-1', department: 'bar', name: 'Bebidas', description: 'Produtos de bar com venda direta.', full_name: 'Bebidas' },
  { id: 'cat-2', department: 'bar', name: 'Snacks', description: 'Produtos de consumo rápido.', full_name: 'Snacks' },
  { id: 'cat-3', department: 'barbershop', name: 'Barbershop', description: 'Categorias raiz da barbearia.', full_name: 'Barbershop' },
  { id: 'cat-4', department: 'barbershop', parent_id: 'cat-3', parent_name: 'Barbershop', name: 'Cosméticos de barbearia', description: 'Consumíveis de uso interno.', full_name: 'Barbershop / Cosméticos de barbearia' },
  { id: 'cat-5', department: 'carwash', name: 'Carwash', description: 'Categorias raiz do carwash.', full_name: 'Carwash' },
  { id: 'cat-6', department: 'carwash', parent_id: 'cat-5', parent_name: 'Carwash', name: 'Detergentes e químicos', description: 'Produtos líquidos de lavagem.', full_name: 'Carwash / Detergentes e químicos' },
]

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    category_id: 'cat-1',
    category_name: 'Bebidas',
    category_path: 'Bebidas',
    department: 'bar',
    item_type: 'resale',
    name: 'Água 500ml',
    sku: 'BAR-001',
    barcode: '258000000001',
    unit: 'bottle',
    sale_price: 75,
    cost_price: 55,
    stock_quantity: 18,
    low_stock_threshold: 5,
    reorder_quantity: 12,
    supplier_name: 'Distribuidora Central',
    storage_location: 'Bar frio',
    image_url: '/branding/placeholders/product-default.svg',
    notes: '',
    active: true,
    low_stock: false,
  },
  {
    id: 'prod-2',
    category_id: 'cat-4',
    category_name: 'Barbershop',
    subcategory_name: 'Cosméticos de barbearia',
    category_path: 'Barbershop / Cosméticos de barbearia',
    department: 'barbershop',
    item_type: 'consumable',
    name: 'Gel de barbear',
    sku: 'BARB-002',
    barcode: '',
    unit: 'unit',
    sale_price: 0,
    cost_price: 320,
    stock_quantity: 2,
    low_stock_threshold: 3,
    reorder_quantity: 6,
    supplier_name: 'Beauty Supply',
    storage_location: 'Armário 1',
    image_url: '/branding/placeholders/product-default.svg',
    notes: 'Uso interno',
    active: true,
    low_stock: true,
  },
  {
    id: 'prod-3',
    category_id: 'cat-6',
    category_name: 'Carwash',
    subcategory_name: 'Detergentes e químicos',
    category_path: 'Carwash / Detergentes e químicos',
    department: 'carwash',
    item_type: 'consumable',
    name: 'Shampoo auto',
    sku: 'CW-001',
    barcode: '',
    unit: 'liter',
    sale_price: 0,
    cost_price: 480,
    stock_quantity: 14,
    low_stock_threshold: 5,
    reorder_quantity: 10,
    supplier_name: 'Wash Pro',
    storage_location: 'Depósito',
    image_url: '/branding/placeholders/product-default.svg',
    notes: '',
    active: true,
    low_stock: false,
  },
]

export const mockServiceCategories: ServiceCategory[] = [
  { id: 'svc-cat-1', department: 'barbershop', name: 'Cortes', description: 'Tipos de corte disponíveis.', active: true, full_name: 'Cortes' },
  { id: 'svc-cat-2', department: 'barbershop', parent_id: 'svc-cat-1', parent_name: 'Cortes', name: 'Clássico', description: 'Cortes tradicionais.', active: true, full_name: 'Cortes / Clássico' },
  { id: 'svc-cat-3', department: 'barbershop', parent_id: 'svc-cat-1', parent_name: 'Cortes', name: 'Fade e modernos', description: 'Cortes modernos e degradê.', active: true, full_name: 'Cortes / Fade e modernos' },
  { id: 'svc-cat-4', department: 'carwash', name: 'Lavagens', description: 'Pacotes de lavagem.', active: true, full_name: 'Lavagens' },
  { id: 'svc-cat-5', department: 'carwash', parent_id: 'svc-cat-4', parent_name: 'Lavagens', name: 'Lavagem premium', description: 'Pacotes premium.', active: true, full_name: 'Lavagens / Lavagem premium' },
]

export const mockStockMovements: StockMovement[] = [
  {
    id: 'mov-1',
    product_id: 'prod-2',
    product_name: 'Gel de barbear',
    product_department: 'barbershop',
    movement_type: 'exit',
    reference_type: 'internal_use',
    reference_code: 'SERV-2026-001',
    quantity: 1,
    unit_cost: 320,
    stock_before: 3,
    stock_after: 2,
    notes: 'Consumo em atendimento',
    created_by_name: 'Admin O Capitão',
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'mov-2',
    product_id: 'prod-3',
    product_name: 'Shampoo auto',
    product_department: 'carwash',
    movement_type: 'entry',
    reference_type: 'purchase',
    reference_code: 'PO-230',
    quantity: 6,
    unit_cost: 450,
    stock_before: 8,
    stock_after: 14,
    notes: 'Reposição semanal',
    created_by_name: 'Harox',
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
]

export const mockServices: Service[] = [
  {
    id: 'srv-1',
    department: 'barbershop',
    category: 'Cortes',
    subcategory: 'Clássico',
    category_ref_id: 'svc-cat-2',
    category_ref_name: 'Clássico',
    name: 'Corte normal',
    duration_minutes: 30,
    price: 350,
    active: true,
  },
  {
    id: 'srv-2',
    department: 'barbershop',
    category: 'Cortes',
    subcategory: 'Fade e modernos',
    category_ref_id: 'svc-cat-3',
    category_ref_name: 'Fade e modernos',
    name: 'Skin fade',
    duration_minutes: 45,
    price: 500,
    active: true,
  },
  {
    id: 'srv-3',
    department: 'carwash',
    category: 'Lavagens',
    subcategory: 'Lavagem premium',
    category_ref_id: 'svc-cat-5',
    category_ref_name: 'Lavagem premium',
    name: 'Lavagem simples',
    duration_minutes: 40,
    price: 450,
    active: true,
  },
]

export const mockCustomers: Customer[] = [
  { id: 'cust-1', full_name: 'Carlos Machava', phone: '84 123 4567', loyalty_points: 42, preferred_barber_name: 'João Capitão', notes: 'Cliente fiel desde 2022. Prefere corte degradê.' },
  { id: 'cust-2', full_name: 'Mário Sitoe', phone: '84 234 5678', loyalty_points: 13, preferred_barber_name: 'Mário Fade', notes: 'Traz o carro ao Sábado.' },
  { id: 'cust-3', full_name: 'Graça Mahlalela', phone: '82 345 6789', loyalty_points: 71, preferred_barber_name: '', notes: 'Lavagem semanal — Toyota RAV4. Cliente VIP.' },
  { id: 'cust-4', full_name: 'Hélio Cossa', phone: '86 456 7890', loyalty_points: 5, preferred_barber_name: 'João Capitão', notes: '' },
  { id: 'cust-5', full_name: 'Rosa Mondlane', phone: '84 567 8901', loyalty_points: 58, preferred_barber_name: 'João Capitão', notes: 'Paga em dinheiro. Sempre pontual.' },
  { id: 'cust-6', full_name: 'Bernardo Nhantumbo', phone: '82 678 9012', loyalty_points: 19, preferred_barber_name: 'Mário Fade', notes: 'Aluno universitário. Desconto 10%.' },
  { id: 'cust-7', full_name: 'Américo Tivane', phone: '86 789 0123', loyalty_points: 33, preferred_barber_name: '', notes: 'Mazda 3 prata — número de matrícula ACP-923-MP.' },
  { id: 'cust-8', full_name: 'Fátima Cumbe', phone: '84 890 1234', loyalty_points: 8, preferred_barber_name: '', notes: 'Prefere atendimento às terças.' },
  { id: 'cust-9', full_name: 'Jorge Macuacua', phone: '82 901 2345', loyalty_points: 2, preferred_barber_name: 'Mário Fade', notes: 'Novo cliente — primeiro corte em Jun 2026.' },
  { id: 'cust-10', full_name: 'Lurdes Bila', phone: '84 012 3456', loyalty_points: 47, preferred_barber_name: '', notes: 'VIP carwash. Honda CRV branco.' },
]

export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1',
    department: 'barbershop',
    customer_name: 'Carlos M.',
    employee_name: 'João Capitão',
    service_name: 'Corte normal',
    scheduled_for: new Date().toISOString(),
    status: 'scheduled',
    payment_status: 'pending',
    walk_in: false,
    price: 350,
  },
  {
    id: 'apt-2',
    department: 'carwash',
    customer_name: 'Mário S.',
    employee_name: 'Equipa Wash',
    service_name: 'Lavagem simples',
    scheduled_for: new Date(Date.now() + 45 * 60000).toISOString(),
    status: 'in_progress',
    payment_status: 'partial',
    walk_in: true,
    price: 450,
  },
]

export const mockVehicles: Vehicle[] = [
  {
    id: 'veh-1',
    customer_name: 'Mário S.',
    registration_number: 'ABP-145-MP',
    brand: 'Toyota',
    model: 'Vitz',
    color: 'Prata',
  },
  {
    id: 'veh-2',
    customer_name: 'Carlos M.',
    registration_number: 'ACP-923-MP',
    brand: 'Mazda',
    model: 'Demio',
    color: 'Azul',
  },
]

export const mockSettings: AppSettings = {
  id: 'settings-1',
  business_name: 'O Capitão',
  legal_name: 'O Capitão, Lda',
  nuit: '',
  address: 'Av. Principal, Maputo',
  city: 'Maputo',
  country: 'Moçambique',
  phone: '+258 84 000 0000',
  email: 'admin@ocapitao.local',
  currency_code: 'MZN',
  currency_symbol: 'MT',
  timezone: 'Africa/Maputo',
  tax_rate: 16,
  appointment_slot_minutes: 30,
  receipt_header: 'Barbershop, Bar e Carwash',
  receipt_footer: 'Obrigado pela preferência.',
  printer_name: '',
  business_hours: 'Segunda a Domingo, 08:00 - 22:00',
  backup_folder: '',
  ssh_tunnel_command: 'ssh -L 5523:127.0.0.1:3306 salacsth@premium342.web-hosting.com -p 21098 -N',
  sync_interval_seconds: 300,
  auto_sync_enabled: true,
  enable_barbershop_module: true,
  enable_bar_module: true,
  enable_carwash_module: true,
  enable_pos_module: true,
  enable_reports_module: true,
  allow_walk_in: true,
  enable_low_stock_alerts: true,
  allow_negative_stock: false,
  require_pin_on_sale: true,
  default_markup_percent: 0,
  default_commission_percent: 0,
  dark_mode: true,
}

export const mockPermissions: PermissionDefinition[] = [
  { id: 'perm-1', module: 'settings', code: 'settings.manage', name: 'Gerir configurações', description: '' },
  { id: 'perm-2', module: 'users', code: 'users.manage', name: 'Gerir utilizadores', description: '' },
  { id: 'perm-3', module: 'inventory', code: 'inventory.manage', name: 'Gerir stock', description: '' },
  { id: 'perm-4', module: 'inventory', code: 'inventory.view', name: 'Consultar stock', description: '' },
  { id: 'perm-5', module: 'reports', code: 'reports.view', name: 'Ver relatórios', description: '' },
]

export const mockRoles: RoleRecord[] = [
  {
    id: 'role-1',
    code: 'admin',
    name: 'Admin',
    description: 'Acesso completo.',
    permissions: mockPermissions,
  },
  {
    id: 'role-2',
    code: 'manager',
    name: 'Gerente',
    description: 'Gestão operacional.',
    permissions: mockPermissions.filter((permission) => permission.code !== 'users.manage'),
  },
]

export const mockUsers: UserRecord[] = [
  {
    id: 1,
    username: 'admin',
    display_name: 'Admin O Capitão',
    email: 'admin@ocapitao.local',
    first_name: 'Admin',
    last_name: 'O Capitão',
    phone: '+258 84 000 0000',
    role: mockRoles[0],
    force_password_change: false,
    is_active: true,
    is_staff: true,
    is_superuser: true,
    is_online: true,
    department: 'management',
    title: 'Administrador',
    commission_rate: 0,
    is_active_employee: true,
    hire_date: new Date().toISOString().slice(0, 10),
    employee_notes: '',
  },
  {
    id: 2,
    username: 'harox',
    display_name: 'Harox',
    email: 'harox@ocapitao.local',
    first_name: 'Harox',
    last_name: '',
    phone: '',
    role: mockRoles[1],
    force_password_change: false,
    is_active: true,
    is_staff: false,
    is_superuser: false,
    is_online: false,
    department: 'management',
    title: 'Operador',
    commission_rate: 0,
    is_active_employee: true,
    hire_date: new Date().toISOString().slice(0, 10),
    employee_notes: '',
  },
]

export const mockUser: AuthUser = {
  id: 1,
  username: 'admin',
  display_name: 'Admin O Capitão',
  email: 'admin@ocapitao.local',
  first_name: 'Admin',
  last_name: 'O Capitão',
  phone: '+258 84 000 0000',
  role: { id: 'role-1', code: 'admin', name: 'Admin', description: 'Acesso completo.', permissions: mockPermissions },
  force_password_change: false,
  is_superuser: true,
}
